version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smuguide-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: smuguide
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"   # host:container
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: